### ISSUE TITLE
Java Module System Support

### ISSUE THREAD

**Issue by webfolderio** [GoodforGod/graalvm-hint#14]
**Describe the solution you'd like**
Yes, my feature request is related to a problem. Currently, I am incorporating your library into a Java project that utilizes the Java Module System. However, the lack of support for this system in your library presents a challenge.

**Describe alternatives you've considered**
To resolve this issue, I kindly request you to consider adding support for the Java Module System to your library. This could be achieved by incorporating a **module-info.java** file or by defining an **Automatic-Module-Name** in the **MANIFEST.MF** file. Either of these additions would allow your library to be used as a module in a modular Java application.

**Comment by GoodforGod** [comment]
Hello, library have no runtime side effects and designed to not leak as dependencies

Are you trying to use this library inside other library as an transitive dependency?

**Comment by GoodforGod** [comment]
```java
module io.goodforgod.graalvm.hint.annotation {

    exports io.goodforgod.graalvm.hint.annotation;
}
```

Will be enough? @webfolderio
