### ISSUE TITLE
Add  groupId and artifactId attributes for @NativeImageHint

### ISSUE THREAD

**Issue by linux-china** [GoodforGod/graalvm-hint#9]
Now hint processor uses package name from classes as groupId, and `hint` as artifactId  for `META-INF/native-image/`.  It's ok for  native image app, such as command line app.  I have an sdk/library and I want use  hint processor to generate native-image configuration json files,   and other normal java apps or native-image apps can use this library both. 

Now groupId and artifactId generated by processor are not fixed, and could be changed  by new classes with hint annotations: 

![image](https://user-images.githubusercontent.com/46711/164525259-fb51fe8c-befb-4c21-bcf9-1657721da81c.png)

Is it possible to add groupId and artifactId for @NativeImageHint?  and processor can use them for native-image configuration files generation.

```
@NativeImageHint(groupId="com.example", artifactId="my-sdk-hint") 
```

**Comment by GoodforGod** [comment]
Yeah, I actually pointed to use that this will be the change, so in example above previous behavior would be:
`org.mvnsearch.demo.domain` and `model` for group and artifact respectfully, now it is `org.mvnsearch.demo.domain.model` and `hint`, so basically nothing really changed, besides some readability in my opinion.

But what is the problem for you?
GraalVM will look for all configs and hints, doesn't matter is this old or new format, so not sure why is it bothers you, can you please elaborate?

**Comment by GoodforGod** [comment]
Also you can actually already pass artifactId and groupId if you pass `graalvm.hint.group` and `graalvm.hint.artifact` to java annotation processor, but it is not that "trivial", but could be done.

Syntax is like `-Akey` where key is `graalvm.hint.group`

More here [doc](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html)

**Comment by linux-china** [comment]
Got.  yes, it works.  I should take a look at the code first :) 

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <compilerArgs>
                        <compilerArg>-Agraalvm.hint.group=org.mvnsearch.demo</compilerArg>
                        <compilerArg>-Agraalvm.hint.artifact=demo-hint</compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
```

**Comment by GoodforGod** [comment]
Great! 
Will leave here Gradle config in case anyone need it and will update documentation with both examples for Gradle and Maven

```
    compileJava {
        options.compilerArgs += [
                '-Agraalvm.hint.group=my.group',
                '-Agraalvm.hint.artifact=myartifact',
        ]
    }
```
